# DB ?? ??
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/gts?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234

# MyBatis ?? (??? ??? ?? ??)
mybatis.config-location=classpath:mybatis-config.xml
mybatis.type-aliases-package=com.example.gts_project
mybatis.mapper-locations=classpath:mappers/*.xml

# [??] ? ?? ??? ?? ???? ??? ???
# prefix? ???? ????? static ??? ??? ????.
spring.mvc.view.prefix=classpath:/static/
spring.mvc.view.suffix=.html

# ?? ??? ?? ??
spring.web.resources.static-locations=classpath:/static/
server.port=8080