# 1. ?? ???(React ?? ??) ?? ??
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/

# 2. MyBatis ?? (????? ??? DB ?? ???)
# Mapper XML ???? ?? ??? ??? ?????
mybatis.mapper-locations=classpath:mappers/*.xml
# VO ??? ??
mybatis.type-aliases-package=com.example.gts_project.vo

# 3. DB ?? ?? (??? ?? @localhost/gts ??)
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/gts
spring.datasource.username=root
spring.datasource.password=1234