# 1. ?? ??? ?? (React ?? ?? ??)
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

# 2. ViewResolver ??
# prefix? /static/?? ??? 'static/static/index.html'? ??? ? ? ????.
# Spring Boot? ?? static ??? ???? ?? ??? ?? ?????.
spring.mvc.view.prefix=/
spring.mvc.view.suffix=.html

# 3. MyBatis ??
# mappers ?? ?? ?? xml ??? ??
mybatis.mapper-locations=classpath:mappers/*.xml
# VO ????? ?? ??? ??? ??
mybatis.type-aliases-package=com.example.gts_project
# DB ??(snake_case)? ?? ??(camelCase)? ?? ??
mybatis.configuration.map-underscore-to-camel-case=true